#!/bin/bash

dotfiles="$HOME/.config"
zshrc="$HOME/.zshrc"

main() {
  setup_zshrc
  install_zsh_plugins
  setup_git

  # Set Zsh as default shell
  chsh -s $(which zsh)
}

setup_zshrc() {
  # If .zshrc doesn't exist, create it.
  if ! [ -f $zshrc ]; then
    echo "$zshrc does not exist."
    touch $zshrc
    echo "Created $zshrc."
  fi

  # If .zshrc isn't initialized, initialize it.
  if grep -q "Start Init -->" $zshrc; then
    echo "ZSH already initialized."
  else
    cat zsh/init.zsh $zshrc > .zshrc.tmp
    mv .zshrc.tmp $zshrc
    echo "Initialized ZSH"
  fi
}

# ZSH Plugins
install_zsh_plugins() {
  # If the plugin directory doesn't exist, create it.
  if [ ! -d $dotfiles/zsh/zsh-plugins ]; then
    echo "$dotfiles/zsh/zsh-plugins doesn't exist, creating it."
    mkdir $dotfiles/zsh/zsh-plugins
  fi

  install_autosuggestions
}

install_autosuggestions() {
  if [ ! -d $dotfiles/zsh/zsh-plugins/zsh-autosuggestions ]; then
    echo "Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions $dotfiles/zsh/zsh-plugins/zsh-autosuggestions
  fi
}

# Git Setup
setup_git() {
  echo "Setting up git."
  git config --global user.email "jmargari@gmail.com"
  git config --global user.name "jeremytondo"
  git config --global --add --bool push.autoSetupRemote true

  # Setup config bare repo to not show untracked files.
  git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
}

main
